drop table dealer;
drop table car;

create table dealer(
    id bigint primary key generated by default as identity,
    name varchar(50) not null,
    address varchar(100) not null,
    created_at timestamp default current_timestamp
);

create table car(
    id bigint primary key generated by default as identity,
    location int not null,
    brand car_brand not null,
    type car_type,
    is_new boolean default false,
    had_accident boolean default false,
    engine_capacity smallint,
    engine_power smallint,
    date_of_fabrication date,
    price float,
    description text
--    constraint dealer_id
--        foreign key(dealer)
--            references dealer(id)
);

insert into dealer (name, address) values
                   ('d1', 'adr1'),
                   ('d2', 'adr2');