create table token_test(
    id int primary key generated by default as identity,
    token varchar(70) not null,
    email varchar(100),
    expiry_date timestamp default current_timestamp + (10 || 'minutes')::interval
);