create table token(
    id int primary key generated by default as identity,
    token varchar(70) not null,
    user_id int,
    expiry_date timestamp default current_timestamp + (10 || 'minutes')::interval
);